### ISSUE TITLE
Newline style

### ISSUE THREAD

**Issue by CylonicRaider** [ThePetriGroup/Petri#5]
`CONTRIBUTING.md` does not prefer any kind of newlines. Prepare for newline hell.

**Comment by CylonicRaider** [comment]
## Evaluation

There are ~~three~~ _~~two~~ depends_ kinds of newlines:
1. _UNIX newlines_:
   - Have the _semantic bonus_, they use the _new line_ character for new lines.
   - Correspond to the `\n` literals in some programming languages (C, JS, Python, _etc_).
   - Are one character less than Windows newlines (particularly interesting for the client side).
2. _Windows newlines_:
   - Are used on a **vast** majority of consumer computers as default (well, that's an argument, isn't it?).
   - Are the newlines of HTTP (UNIX-style ones are _tolerated_); are "normalized to" while submitting HTML forms (they arrive with Windows-style newlines).
3. _Mac newlines_:
   - Obsolete.
   - Used only in particularly weird contexts.
   - Included as a joke :smiling_imp:.

While we all can easily configure our IDE's/text editors/_[insert arbitrary way of entering computer data]_ to any of them (I hope), we should still have them consistent to avoid all-lines-changed merges _etc_.

As evident, I'm not entirely unbiased, but that's my opinion.

**Comment by jedevc** [comment]
Personally, I think Unix style is simpler, neater and is used by a majority (not sure though). I vote Unix.

**Comment by CylonicRaider** [comment]
I'm personally quite sure UNIX will win (how many of us are _not_ on Linux?).

**Comment by Kaliom** [comment]
Ill go with Unix style, I already set my IDE to it.

**Comment by MicheleCastrovilli** [comment]
Unix style, since it's already the majority of os'es in this group.

**Comment by CylonicRaider** [comment]
I'll leave it up to @jedevc to change CONTRIBUTING.

**Comment by jedevc** [comment]
I've fixed CONTRIBUTING.md now. UNIX FOR THE WIN!
